import Head from "next/head";
import Image from "next/image";

import styles from "../styles/Home.module.css";
import ReactMarkdown from "react-markdown";
import React, { useInput } from "react";
import TextInput from "../components/text-input";
import MarkdownDisplay from "../components/markdown-display";
import SplitView from "../components/split-view";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="text-2xl bg-red-200">Hello Friend</div>
      <ReactMarkdown>Hello **World** in ***Markdown***</ReactMarkdown>
      <div>
        <SplitView
          left={<div className="m-4">Left item</div>}
          right={<div className="m-4">Right Item</div>}
        />
      </div>
    </div>
  );
}
