import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import ReactMarkdown from "react-markdown";
import React, { useInput, useState, createContext, useContext } from "react";
import TextInput from "../components/text-view";
import MarkdownDisplay from "../components/markdown-view";
import SplitView from "../components/split-view";
import TopBar from "../components/topbar";

export const TextDataContext = createContext();

export default function Home() {
  const [textData, setTextData] = useState("Default Text");

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" /> 
        <link
          href="https://fonts.googleapis.com/css2?family=Manrope:wght@300;400;500;600;700&display=swap"
          rel="stylesheet"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Source+Code+Pro:ital,wght@0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
          rel="stylesheet"
        />
      </Head>

      <div className="flex flex-col min-h-screen">
        <TopBar />
        <div className="flex flex-grow">
          <SplitView
            left={
              <TextDataContext.Provider value={{ textData, setTextData }}>
                <TextInput />
              </TextDataContext.Provider>
            }
            right={
              <div className="">
                <TextDataContext.Provider value={{ textData, setTextData }}>
                  <MarkdownDisplay />
                </TextDataContext.Provider>
              </div>
            }
          />
        </div>
      </div>
    </div>
  );
}
